version: "3.8"

services:
  fury-api:
    container_name: fury-api
    build:
      context: ./api
      dockerfile: ./deploy/docker/fury_api.Dockerfile
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    ports:
      - "${PORT:-3000}:3000"
      - "5678:5678"
    command: >
      sh -c "/opt/pysetup/.venv/bin/alembic --config /app/src/fury_api/lib/db/alembic.ini upgrade head && python -m fury_api"
    networks:
      - fury-network
    environment:
      # Server
      FURY_API_SERVER_HOST: "0.0.0.0"
      FURY_API_SERVER_RELOAD: "true"
      FURY_API_APP_ENVIRONMENT: "dev"
      # Database
      FURY_DB_URL: postgresql+psycopg://postgres:postgres@postgres:5432/beyond-gravity-local
      # DB Schema
      FURY_DB_SCHEMA: platform
      FURY_API_ELASTIC_APM_ENABLED: "false"
      FURY_API_DEVEX_ENABLED: "true"

  postgres:
    image: postgres:15
    container_name: fury-postgres
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fury-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beyond-gravity-local

  webapp:
    container_name: beyond-gravity-webapp
    build:
      context: ./webapp
      dockerfile: ./deploy/Dockerfile
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "3001:3001"
    environment:
      # The web app runs in the browser; expose API on host port 3000
      NEXT_PUBLIC_API_URL: "http://localhost:3000"
      # Toggle mocks/auth locally as needed
      NEXT_PUBLIC_USE_MOCKS: "false"
      NEXT_PUBLIC_SKIP_AUTH: "false"
    networks:
      - fury-network
    depends_on:
      - fury-api

networks:
  fury-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
