apiVersion: v2
name: fury-api
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

# Add PostgreSQL as a dependency
dependencies:
  - name: postgresql
    version: 15.0.0   # Update to the desired PostgreSQL version
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
