apiVersion: v1
kind: Service
metadata:
  name: {{ include "fury-api.fullname" . }}
  labels:
    {{- include "fury-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    {{- include "fury-api.selectorLabels" . | nindent 4 }}
